### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "3d4bb25cdb7b418f94020a5d3e6c12cf",
  "accountNumber": "1000000002",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/d0a4c1313306464489d26eb824a2cc5a
